platform :ios, '9.3'

# ignore all warnings from all pods
inhibit_all_warnings!

source 'https://github.com/WaltzApp/Podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RNWaltz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'WaltzAccess', :inhibit_warnings => true

end
